### ISSUE TITLE
Remove Unobtainable items from EMI/JEI

### ISSUE THREAD

**Issue by Qwerty97475** [meeprdib/OdysseyNexus#61]

**Comment by Qwerty97475** [comment]
Inscription table
Scroll forge
arcane anvil
alchemist cauldron
uranium ingot, nugget, block, sheet, raw, raw block, ore
tungsten ingot, nugget, sheet, block
wolfram ore, raw, raw block
constantan ingot, nugget, sheet, block
wrought iron ingot, nugget, sheet, block
all 5 types of ink
ancient knowledge fragment

**Comment by Qwerty97475** [comment]
Also many items from Create vintage Improvements are unobtainable (mainly metal compat springs and stuff)

**Comment by meeprdib** [comment]
I've decided to keep in ISS workbenches as cosmetic only blocks, and I don't want to hide any materials added by Unify because I still haven't figured out which ones I want to keep or not. I have ideas for the ISS inks too, but will probably remove the ancient knowledge fragment. Will look into removing all of the VI items too, I tried removing them earlier but ig the script didn't work.
